### ISSUE TITLE
bee  test fails

### ISSUE THREAD

**Issue by joeblew99** [peterhellberg/emojilib#1]
this is super cool :)

I really want to try to get this working with Ebiten.
https://github.com/hajimehoshi/ebiten

Can you check this error ?

````
cd emojilib/
x-MacBook-Pro:emojilib apple$ go generate
x-MacBook-Pro:emojilib apple$ ls
LICENSE			README.md		_generator		emojilib.go		emojilib_test.go	generated.go
x-MacBook-Pro:emojilib apple$ go test 
--- FAIL: TestFind (0.00s)
	emojilib_test.go:19: unexpected error
	emojilib_test.go:23: Find("bee") = "", nil, want "🐝", nil
FAIL
exit status 1
FAIL	github.com/peterhellberg/emojilib	0.011s


````

**Comment by peterhellberg** [comment]
I've now generated a new version of `generated.go` (commit 41920917e2710c9f0ec22d29db182f60e7ed9d11) and fixed the test case.

The 🐝 emoji was renamed from “bee” to “honeybee” in the [emojis.json](https://raw.githubusercontent.com/muan/emojilib/master/emojis.json)

You don't need to run go generate in order to use this package, just `import "github.com/peterhellberg/emojilib"` in your own project.
